Default: &defaults
  database: YesodCrud.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: YesodCrud_test.sqlite3
  <<: *defaults

Staging:
  database: YesodCrud_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: YesodCrud_production.sqlite3
  poolsize: 100
  <<: *defaults
